M48
; DRILL file {KiCad (6.0.11)} date Sun 12 Feb 2023 12:55:56 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-12T12:55:56-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1575
%
G90
G05
T1
X3.7844Y-4.2797
X3.7844Y-4.3978
T2
X5.1213Y-4.4008
X5.5213Y-4.4008
T3
X6.335Y-3.7579
T4
X5.3213Y-4.4008
T0
M30
